version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  load-generator:
    build:
      context: .
      dockerfile: packages/load-generator/Dockerfile
    container_name: load-generator
    ports:
      - "3001:3001"
    depends_on:
      - kafka
    command: npm run dev

  hypervisor-consumer:
    build:
      context: .
      dockerfile: packages/hypervisor/Dockerfile
    container_name: hypervisor-consumer
    depends_on:
      - kafka
    command: npm run dev:consumer

  hypervisor-producer:
    build:
      context: .
      dockerfile: packages/hypervisor/Dockerfile
    container_name: hypervisor-producer
    depends_on:
      - kafka
    command: npm run dev:producer
